# Generated by Django 3.1.3 on 2020-11-26 13:32

import account.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('roll_no', models.CharField(max_length=11, unique=True)),
                ('branch', models.CharField(choices=[('cse', 'CSE'), ('it', 'IT'), ('ece', 'ECE'), ('ee', 'EE'), ('me', 'ME'), ('ce', 'CE'), ('che', 'CHE')], max_length=3)),
                ('year', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV')], max_length=1)),
                ('areas_of_interest', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'WebDev'), ('2', 'AppDev'), ('3', 'ML'), ('4', 'AI'), ('5', 'Electronics'), ('6', 'Electrical')], max_length=11)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=account.models.get_default_profile_image, max_length=255, null=True, upload_to=account.models.get_profile_image_filepath)),
                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
