# Generated by Django 3.1.3 on 2020-11-28 05:22

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201126_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cover_image',
            field=models.ImageField(blank=True, default=account.models.get_default_cover_image, max_length=255, null=True, upload_to=account.models.get_cover_image_filepath),
        ),
    ]
