# Generated by Django 3.1.3 on 2020-11-30 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201129_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issued_book',
            old_name='user',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='issued_book',
            name='last_date',
            field=models.DateField(default=datetime.date(2021, 2, 28)),
        ),
    ]
