# Generated by Django 3.1.4 on 2020-12-01 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201130_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued_book',
            name='last_date',
            field=models.DateField(default=datetime.date(2021, 3, 1)),
        ),
    ]
