# Generated by Django 3.1.4 on 2020-12-02 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201201_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued_book',
            name='last_date',
            field=models.DateField(default=datetime.date(2021, 3, 2)),
        ),
    ]
