# Generated by Django 3.1.3 on 2020-12-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201205_2017'),
        ('main', '0006_auto_20201202_2029'),
    ]

    operations = [
    ]
