# Generated by Django 3.1.3 on 2020-12-28 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20201206_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued_book',
            name='last_date',
            field=models.DateField(default=datetime.date(2021, 3, 28)),
        ),
    ]
